# Includes all of the IK Classification related classes.
require 'graph'
require 'graph_constants'
require 'ik_classifications/base'
require 'ik_classifications/null_classification'
require 'ik_classifications/order_classification'
require 'ik_classifications/absolute_size_classification'
require 'ik_classifications/relative_size_classification'
require 'ik_classifications/planarity_classification'
require 'ik_classifications/minor_of_classification'
require 'ik_classifications/contains_minor_classification'
require 'ik_classifications/classifier'
